import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root=new URL('../',import.meta.url),files=['src/research/engine.mjs','src/research/policy.mjs','src/research/catalog.mjs','src/research/transport.mjs','src/research/receiver-worker.mjs','src/research/deepseek-live.mjs','src/research/validation-score.mjs','src/research/sealed-request-v4.mjs','src/research/controlled-execution-v4.mjs','src/research/local-program.mjs','src/research/financial-execution.mjs','src/research/financial-score.mjs','fixtures/research/references.json','fixtures/validation-v3/cases.json','fixtures/validation-v3/labels.json','fixtures/finqa-v4/cases.json','fixtures/finqa-v4/labels.json','fixtures/finqa-v4/provenance.json','scripts/prepare-finqa.mjs','scripts/run-v4.mjs','package-lock.json'];
const hashes={};for(const file of files)hashes[file]=createHash('sha256').update(await readFile(new URL(file,root))).digest('hex');
for(const suite of ['finqa','controls']){
 const methods=suite==='finqa'?['eager_allowed','requested_cells','local_program']:['joint','allowed_eager','numeric_prefetch','no_acquisition'];
 const cases=suite==='finqa'?40:32,out=new URL(`evidence/validation-v4/${suite}/`,root);await mkdir(out,{recursive:true});
 const p={id:`v4-${suite}-20260927`,suite,frozenAt:new Date().toISOString(),cases,methods,repetitions:2,jobs:cases*methods.length*2,concurrency:4,model:'deepseek-flash',temperature:0,maxTokens:suite==='finqa'?900:650,
  primary:suite==='finqa'?'Correct numerical answer against original FinQA exe_ans, absolute tolerance 0.00005, all planned tasks in denominator.':'Strict structured outcome under unchanged v3 labels; all planned tasks included.',
  source:suite==='finqa'?'40 selected test pages from FinQA: 38 company-year reports, 28 companies; fixed eligibility and hash ordering. Restricted table-only subset.':'Re-evaluation of the 32 previously published v3 cases; this is a stronger-control study, not a new holdout.',
  controls:suite==='finqa'?'Same schema, question, interpreter, model and numeric evaluator. eager_allowed sends all numeric cells. requested_cells lets the model request up to 12 cells once and restricts computation to those cells. local_program sends no numeric cell values and executes the returned bounded expression locally. All final answers are assembled locally.':'All four use identical local rules, prompts and reference projection. allowed_eager sends all permitted business fields, excluding all five private-field types. numeric_prefetch adds all registered numeric task fields to the initial view. no_acquisition disables requests. joint acquires fields when requested.',
  development:suite==='finqa'?'Three development-split cases used for smoke testing. The first pilot exposed ratio/sign convention errors; one uniform instruction was added for all methods before test freeze. No test model outputs observed before freeze.':'Three v3 inputs used for integration checks; neither new control changes the model or local rules.',
  secondary:suite==='finqa'?['unique and cumulative raw numeric cells transmitted','cells outside original gold program (not semantic privacy)','tokens','calls','wall runtime']:['extra allowed fields transmitted under frozen labels','tokens','calls','wall runtime'],
  inference:suite==='finqa'?'Aggregate repeats within case; paired cluster bootstrap by company-year report, 4000 draws. Descriptive uncertainty for this selected subset; no general-population or non-inferiority claim.':'Aggregate repetitions within case; paired case bootstrap, 4000 draws, descriptive for this author-designed set.',
  failures:'No model-result based selection or relabeling. Provider/parse/program errors remain failures. Resume only absent job IDs. No best-of selection.',
  scope:'No human text-quality score, cryptographic privacy, semantic non-disclosure, data-minimization optimality, or external-system superiority claim.',hashes};
 await writeFile(new URL('protocol.json',out),JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({suite,jobs:p.jobs,frozenAt:p.frozenAt}));
}
