import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {makeRepairCases,REPAIR_METHODS,MUTATIONS} from '../src/research/repair-workloads.mjs';
const root=new URL('../',import.meta.url),out=new URL('evidence/validation-v7/',root);
await mkdir(out,{recursive:true});await mkdir(new URL('fixtures/repair-v7/',root),{recursive:true});
try{await readFile(new URL('protocol.json',out));throw Error('Protocol already exists; do not silently refreeze');}catch(e){if(e.code!=='ENOENT')throw e;}
await writeFile(new URL('fixtures/repair-v7/cases.json',root),JSON.stringify(makeRepairCases({count:24}),null,2)+'\n');
await writeFile(new URL('fixtures/repair-v7/development.json',root),JSON.stringify(makeRepairCases({development:true,count:4}),null,2)+'\n');
const files=['src/research/disclosure-frontier.mjs','src/research/repair-workloads.mjs','src/research/repair-execution.mjs','src/research/repair-receiver.mjs','src/research/freshctx-bridge.mjs','scripts/freshctx-boundary.py','scripts/run-v7.mjs','scripts/verify-v7.mjs','requirements-v7.txt','test/disclosure-frontier.test.mjs','test/repair-execution.test.mjs','fixtures/repair-v7/cases.json','fixtures/repair-v7/development.json'];
const hashes={};for(const file of files)hashes[file]=createHash('sha256').update(await readFile(new URL(file,root))).digest('hex');
const protocol={id:'v7-dynamic-disclosure-repair',frozenAt:new Date().toISOString(),methods:REPAIR_METHODS,eventTypes:MUTATIONS,cases:288,executions:1728,design:'4 registered operation orders x 6 numeric parameterizations x 12 event types x 6 methods. Four structural templates, not 1728 independent real-world tasks.',development:'48 author-created development cells; not included in final totals.',source:'Synthetic finite-operator system experiment. Real loopback HTTP requests; no new LLM calls.',methodOrder:'rotated by case index',primaryMetrics:['contract-consistent completion or required block','stale dispatches','unauthorized dispatches','distinct recipient/field/version disclosures','remote operation executions'],privacyMetric:'Operational count, not semantic privacy loss. Derived aggregates count. History is monotone; repeats still contribute bandwidth but not a second identical disclosure token.',guarantees:'Complete registered dependencies and trusted synchronous local dispatch required. No global transactions, arbitrary tool safety, semantic necessity inference, or optimum over unknown future steps.',externalBaseline:{name:'FreshCtx',version:'0.16.0',wheelSha256:'695e9b37580807f0138ed017003251a619c26e99aa07c3e50cee8cf013150017',source:'https://github.com/Hyperwise-LLC/freshctx',configuration:'Full decision dependencies; block policy. Restart or selective repair is implemented by our wrapper. No claim that FreshCtx prescribes a full restart.'},timing:'End-to-end measured elapsed includes bridge overhead for FreshCtx. No cross-language speedup claim. Primary cost is actual HTTP executions.',hashes};
await writeFile(new URL('protocol.json',out),JSON.stringify(protocol,null,2)+'\n');console.log(JSON.stringify({cases:protocol.cases,executions:protocol.executions,frozenAt:protocol.frozenAt}));
