import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {hash} from '../src/research/local-program.mjs';
import {METHODS,CONDITIONS} from '../src/research/model-repair-v8.mjs';
const root=new URL('../',import.meta.url),out=new URL('evidence/validation-v8/',root);await mkdir(out,{recursive:true});
try{await readFile(new URL('protocol.json',out));throw Error('PROTOCOL_ALREADY_EXISTS');}catch(e){if(e.code!=='ENOENT')throw e;}
const files=['src/research/model-repair-v8.mjs','src/research/budget-frontier-v8.mjs','src/research/local-program.mjs','src/research/deepseek-live.mjs','scripts/run-v8.mjs','scripts/verify-v8.mjs','scripts/prepare-v8.mjs','test/model-repair-v8.test.mjs',...['cases','development','labels','provenance'].map(x=>'fixtures/model-repair-v8/'+x+'.json')];
const hashes={};for(const p of files)hashes[p]=hash(await readFile(new URL(p,root),'utf8'));
const protocol={id:'v8-model-graph-disclosure-budget',frozenAt:new Date().toISOString(),cases:24,reports:24,repeats:2,modelCallsPlanned:96,methods:METHODS,conditions:CONDITIONS,armsPlanned:1440,model:'deepseek-flash',temperature:0,provider:'https://api.deepseek.com/chat/completions',promptLocation:'src/research/model-repair-v8.mjs: MODEL_SYSTEM, MODEL_TOOLS',pairedDesign:'Each observed model graph and its two actual provider calls are shared across all 30 controller arms; do not count a shared prefix as 30 distinct LLM conversations. Method order rotates by source-case and repeat.',events:'After max(1,floor(model_nodes/2)) nodes: update first source of model node 0 by x*1.01+0.5; unrelated condition updates first sorted unused field, otherwise recorded unavailable; withdrawal removes registered local add/subtract capability. All interventions controlled and model-label-blind.',capabilities:'all_local: all six operations local; other conditions: local add/subtract, remote all six. Deployment profiles, not inherent arithmetic limitations.',budget:'At each post-change phase, at most floor((1+slack)*greedy numeric-field transmissions for that known suffix). Remaining budget carried across replanning. Default slack 0, sensitivity .10/.25. No byte, across-change, or unknown-future bound.',evaluation:'Independent expression evaluator; source-version and receipt verification. Original FinQA correctness separately scored. Changed-source targets evaluate original gold expression on intervened numeric cells. Relative/absolute tolerance 5e-5. Every model failure retained.',development:'Four earlier development questions, 8 actual pilot calls and 120 pilot arms; excluded from the prospective batch.',analysis:'Report all conditions and arms, paired outcomes, model program correctness, executions, numeric disclosures, repeated numeric fields, actual payload bytes, search cost and actual provider calls. No optional stopping. No independent-sample significance from 1440 dependent arms.',limitation:'Registered pure finite operators and equivalent views; trusted synchronous local check/serialization. Public financial data; no production, adversarial privacy, global-transaction or arbitrary-agent guarantee.',hashes};
await writeFile(new URL('protocol.json',out),JSON.stringify(protocol,null,2)+'\n');console.log(JSON.stringify({frozen:protocol.id,files:files.length,graphs:48,arms:1440}));
